---
name: nfs-server
director_uuid:  (( merge ))

compilation:
  workers: 1
  network: nfsvolume-subnet
  reuse_compilation_vms: true
  cloud_properties:
    availability_zone: us-east-1c
    instance_type: m3.large
    ephemeral_disk:
      size: 10000 # in MB
      type: gp2

jobs:
- name: nfstestserver
  instances: 1
  networks:
  - name: nfsvolume-subnet
    default: [dns, gateway]
    static_ips: (( nfs-test-server.ips ))
  - name: public
    static_ips: (( nfs-test-server.public_ips ))
  resource_pool: medium
  templates:
  - release: nfs-volume
    name: nfstestserver
  persistent_disk: 25000
  properties:
    nfstestserver: {}

networks:
- name: nfsvolume-subnet
  subnets: (( merge ))
  type: manual
- name: public
  type: vip

properties:
  nfstestserver: {}

releases:
  - name: nfs-volume
    version: latest

resource_pools:
  - name: large
    network: nfsvolume-subnet
    stemcell: (( merge ))
    cloud_properties: (( merge ))

  - name: medium
    network: nfsvolume-subnet
    stemcell: (( merge ))
    cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

nfs-test-server: (( merge ))